CREATE TABLE users(
  "userId" SERIAL PRIMARY KEY,
  "username" VARCHAR(64) UNIQUE NOT NULL,
  "password" CHAR(95) NOT NULL,
  "createAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updateAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE servers(
  "serverId" SERIAL PRIMARY KEY,
  "ownerId" INT NOT NULL,
  "key" VARCHAR(16) UNIQUE NOT NULL,
  "name" VARCHAR(64) NOT NULL,
  "createAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updateAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.servers ADD FOREIGN KEY("ownerId") REFERENCES public.users("userId");

CREATE TABLE event_types(
  "typeId" SERIAL PRIMARY KEY,
  "serverId" INT NOT NULL,
  "name" VARCHAR(64) NOT NULL,
  "createAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updateAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.event_types ADD FOREIGN KEY("serverId") REFERENCES public.servers("serverId");

CREATE TYPE ACTION AS ENUM ('QUERY','MUTATION','SUBSCRIPTION');

CREATE TABLE events(
  "eventType" SERIAL PRIMARY KEY,
  "serverId" INT NOT NULL,
  "typeId" INT NOT NULL,
  "action" ACTION DEFAULT 'QUERY',
  "additionInfo" JSON,
  "operationName" VARCHAR(64) NOT NULL,
  "duration" NUMERIC(10,4),
  "createAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updateAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.events ADD FOREIGN KEY("typeId") REFERENCES public.event_types("typeId");
